config/routes.rb
Rails.application.routes.draw do
  root 'place#index'

  namespace :place do
    get 'list'
  end

  resources :place, :only => [ :index, :show, :create, :destroy ]
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/place_controller.rb
class PlaceController < ApplicationController
  before_action :set_place, only: [:show, :destroy]

  def index
    @places = Place.all
  end

  def show
        @hash = Gmaps4rails.build_markers(@place) do |place,marker|
      marker.lat place.latitude
      marker.lng place.longitude
      marker.json({title: place.name})
    end
  end

  def list
    keyword = params[:search]
    @client = GooglePlaces::Client.new('AIzaSyCG0DobFXZ7OVcFVGf-nrJaXHNKAY4Slrg', :language => 'ja')
    @places = @client.spots_by_query( keyword )
  end

  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to place_index_path, notice: "#{@place.name} の位置情報を保存しました" }
      else
        format.html { render :index, notice: "#{@place.name} の位置情報を保存できませんでした" }
      end
    end
  end

  def destroy
    @place.destroy

    respond_to do |format|
      format.html { redirect_to place_index_path, notice: "#{@place.name} の位置情報を削除しました" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude, :address)
    end

end

app/controllers/test.rb
  def car_use
    show_one

     respond_to do |format|
      format.html
      format.pdf do

        # Thin ReportsでPDFを作成
        # 先ほどEditorで作ったtlfファイルを読み込む
        report = ThinReports::Report.new :layout => "app/pdfs/order_pdf.tlf"

          # 1ページ目を開始
        report.start_new_page
         link_date = Gw.datetime_to_date(@item.st_at)

        # 開始日時、終了日時の文字列
        time_show = @item.time_show

        today = Date.today.to_time
        st_date = "#{I18n.l @item.st_at.to_date, format: :date5}"
        ed_date = "#{I18n.l @item.ed_at.to_date, format: :date5}"
        visit = @item.title
        place = @item.place

        report.page.item(:today).value(today)
        report.page.item(:st_day).value(st_date)
        report.page.item(:ed_day).value(ed_date)
        report.page.item(:visit).value(visit)
        report.page.item(:place).value(place)

         @item.schedule_users.each do |user|
           user = System::User.where("id=#{user.uid}").first
           report.list(:user).add_row do |row|
             row.values username: user.name
           end
         end

        # ブラウザでPDFを表示する
        # disposition: "inline" によりダウンロードではなく表示させている
                send_data report.generate, filename: '社有車使用届.pdf',
                                           type: 'application/pdf',
                                           disposition: 'inline'
     end

    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/place_helper.rb
module PlaceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCG0DobFXZ7OVcFVGf-nrJaXHNKAY4Slrg&language=ja&region=JP"></script>
  <script src="/app/assets/javascripts/markerclusterer_packaged.js" type="text/javascript"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Project name</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
        <form class="navbar-form navbar-left">
          <input type="text" class="form-control col-lg-8" placeholder="Search">
        </form>
      </div><!--/.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar -->

<%= yield %>

</body>
</html>

app/views/place/index.html.erb
<h1>位置情報を検索してみよう</h1>

<div class="col-md-6">
  <%= form_tag place_list_path, :role =>"form", :method => :get do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], { :class => "form-control", :required => true, } %>
      <%= button_tag( {:type => "submit", :name => nil, :class => "btn btn-default" } ) do %>
        <span class="glyphicon glyphicon-search">キーワード検索</span>
      <% end %>
    </div>
  <% end %>
</div>

<div class="col-md-12">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Address</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @places.each do |place| %>
        <tr>
          <td><%= place.name %></td>
          <td><%= place.latitude %></td>
          <td><%= place.longitude %></td>
          <td><%= place.address %></td>
          <td><%= link_to ( place ), :title => "show" do %>
            <span class="glyphicon glyphicon-stats"></span>
          <% end %></td>
          <td><%= link_to( place, method: :delete, data: { confirm: "#{place.name} の位置情報を削除します" }, :title => "delete" ) do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/place/list.html.erb
<h1>希望の場所は見つかったかな?</h1>

<div class="col-md-12">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Address</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @places.each do |place| %>
        <tr>
          <td><%= place.name %></td>
          <td><%= place.lat %></td>
          <td><%= place.lng %></td>
          <td><%= place.address_components  %></td>
          <td><%= link_to( '登録', place_index_path( :place => { :name      => place.name,
                                                                 :latitude  => place.lat,
                                                                 :longitude => place.lng,
                                                                 :address   => place.address_components, } ),:method => 'post' ) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <button type="button" class="btn pull-right btn-lg btn-default">
    <%= link_to 'Back', place_index_path %>
  </button>

</div>

app/views/place/show.html.erb
<div class="col-md-12">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Address</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @place.name %></td>
        <td><%= @place.latitude %></td>
        <td><%= @place.longitude %></td>
        <td><%= @place.address %></td>
      </tr>
    </tbody>
  </table>
  
  <div class="map_container">
    <div id="map" class="map_canvas"></div>
  </div>

  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(12);
      handler.map.centerOn(marker);
    });
  </script>

  <button type="button" class="btn pull-right btn-lg btn-default">
    <%= link_to 'Back', place_index_path %>
  </button>

</div>